import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Account } from '../../shared/models/account.model';

@Injectable({
  providedIn: 'root',
})
export class AccountsService {
  private _accounts: Account[] = [
    {
      id: '0',
      firstName: 'Robert',
      middleName: 'Karol',
      lastName: 'Skrzypczak',
      sex: { id: '1', name: 'Male' },
      birthDate: '1999-03-12',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      email: 'robert.skrzypczak@gmail.com',
      image: 'assets/icons/icon14.png',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '1',
        name: 'Frontend Developer',
        description: 'Frontend Developer',
        creationDate: '2022-01-20',
        count: 1,
        active: true,
      },
      employmentDate: '2021-08-15',
      workingTime: 40,
      active: true,
      password: 'abc',
      phoneNumber: '777-777-777',
      privateEmail: 'bob@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '1',
      firstName: 'Beata',
      middleName: '',
      lastName: 'Iwan',
      email: 'beata.iwan@gmail.com',
      image: 'assets/icons/icon4.png',
      pesel: 1231231231,
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '2',
        name: 'Product Designer',
        description: 'Product Designer',
        creationDate: '2022-01-20',
        count: 1,
        archiveDate: '2022-10-10',
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      active: true,
      password: 'abc',
      sex: { id: '2', name: 'Female' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'iwaaaaaaaan@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '2',
      firstName: 'Joanna',
      middleName: '',
      lastName: 'Malawska',
      email: 'joanna.malawska@gmail.com',
      image: 'assets/icons/icon8.png',
      pesel: 1231231231,
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '2',
        name: 'Product Designer',
        description: 'Product Designer',
        creationDate: '2022-01-20',
        count: 1,
        archiveDate: '2022-10-10',
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      active: true,
      password: 'abc',
      sex: { id: '2', name: 'Female' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'asia@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '3',
      firstName: 'Anna',
      middleName: '',
      lastName: 'Nowak',
      email: 'anna.nowak@gmail.com',
      image: 'assets/icons/icon7.png',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '2',
        name: 'Product Designer',
        description: 'Product Designer',
        creationDate: '2022-01-20',
        count: 1,
        archiveDate: '2022-10-10',
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      exitDate: '2022-09-01',
      active: false,
      password: 'abc',
      sex: { id: '2', name: 'Female' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'nowczi@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '4',
      firstName: 'Paweł',
      middleName: '',
      lastName: 'Szymański',
      email: 'pawel.szymanski@gmail.com',
      image: 'assets/icons/icon19.png',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '2',
        name: 'Product Designer',
        description: 'Product Designer',
        creationDate: '2022-01-20',
        count: 1,
        archiveDate: '2022-10-10',
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      active: true,
      password: 'abc',
      sex: { id: '1', name: 'Male' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'szymon@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '5',
      firstName: 'Maria',
      middleName: '',
      lastName: 'Wiśniewska',
      email: 'maria.wisniewska@gmail.com',
      image: 'assets/icons/icon3.png',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '1',
        name: 'Frontend Developer',
        description: 'Frontend Developer',
        creationDate: '2022-01-20',
        count: 1,
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      exitDate: '2022-09-01',
      active: false,
      password: 'abc',
      sex: { id: '2', name: 'Female' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'marthaaa@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '6',
      firstName: 'Jan',
      middleName: '',
      email: 'jan.kowalski@gmail.com',
      lastName: 'Kowalski',
      image: 'assets/icons/icon13.png',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '1',
        name: 'Frontend Developer',
        description: 'Frontend Developer',
        creationDate: '2022-01-20',
        count: 1,
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      exitDate: '2022-09-01',
      active: false,
      password: 'abc',
      sex: { id: '1', name: 'Male' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'kowalski@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '7',
      firstName: 'Emil',
      middleName: '',
      lastName: 'Zieliński',
      email: 'emil.zielinski@gmail.com',
      image: 'assets/icons/icon18.png',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '2',
        name: 'Product Designer',
        description: 'Product Designer',
        creationDate: '2022-01-20',
        count: 1,
        archiveDate: '2022-10-10',
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      active: true,
      password: 'abc',
      sex: { id: '1', name: 'Male' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'zielu@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
    {
      id: '8',
      firstName: 'Krystian',
      middleName: '',
      lastName: 'Kowalczyk',
      email: 'krystian.kowalczyk@gmail.com',
      image: 'assets/icons/icon16.png',
      birthPlace: 'Kraków',
      idCardNumber: 'CCC675432',
      pesel: 1231231231,
      contractType: { id: '4', name: 'B2B' },
      rate: 35,
      payday: 1,
      position: {
        id: '2',
        name: 'Product Designer',
        description: 'Product Designer',
        creationDate: '2022-01-20',
        count: 1,
        archiveDate: '2022-10-10',
        active: true,
      },
      employmentDate: '2022-07-01',
      workingTime: 40,
      active: true,
      password: 'abc',
      sex: { id: '1', name: 'Male' },
      birthDate: '1999-03-12',
      phoneNumber: '777-777-777',
      privateEmail: 'kowal-@gmail.com',
      street: 'Nowowiejska',
      houseNumber: '17',
      apartmentNumber: '43',
      city: 'Warszawa',
      postalCode: '35-323',
      country: {
        name: '🇵🇱 Poland',
        id: '175',
      },
      accountNumber: '90 0023 0231 2145 3443 2133 2300',
    },
  ];

  constructor() {}

  getAccount(id: string): Observable<Account> {
    const account = this._accounts.find(account => account.id === id);
    return of(account as Account);
  }
}
